config/urls.py
from django.contrib import admin
from django.urls import include, path

# De la app homepage y de su modulo views importamos la clase Index
from homepage.views import Index


# Las siguientes dos lineas de codigo hace que sea posible trabajar durante el desarrollo de la apliacion con archivos multimedia 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('erp_v_i.urls')),
    path('', Index.as_view(), name="index"),
    path('login/',include('login.urls')),
]

# La siguiente linea de codigo hace que sea posible trabajar durante el desarrollo de la apliacion con archivos multimedia 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

erp_v_i/urls.py
from django.urls import path

# importacion de las vistas basadas en clase referentes al apartado de categoria 
from .views import Categoria_Lista, Categoria_Crear, Categoria_Editar, Categoria_Eliminar 

# importacion de las vista panel principal 
from .views import Panel_Principal 


# importacion de las vistas basadas en clase referentes al apartado de Producto 
from .views import Producto_Lista, Producto_Crear, Producto_Editar, Producto_Eliminar

# importacion de las vistas basadas en clase referentes al apartado de Cliente 
from .views import Cliente_Lista, Cliente_Crear, Cliente_Editar, Cliente_Eliminar, Cliente_Ver

# importacion de las vistas referentes al apartado de Venta y Detalle de Venta 
from .views import Venta_Crear, Venta_Lista, Detalle_De_Venta_Ver, Venta_Eliminar

# al colocar el app_name como erp permite especificar mas la url, por ende quedareia erp:categoria_lista cuando se use en el template
app_name = "erp"

urlpatterns = [

    # Vista Basadas en clase | Apartado Categorias 
    path('categoria/lista/', Categoria_Lista.as_view(), name="Categoria_Lista"),
    path('categoria/crear/', Categoria_Crear.as_view(), name="Categoria_Crear"),
    path('categoria/editar/<int:pk>/', Categoria_Editar.as_view(), name="Categoria_Editar"),
    path('categoria/eliminar/<int:pk>/', Categoria_Eliminar.as_view(), name="Categoria_Eliminar"),

    path('panel-principal/', Panel_Principal, name="Panel_Principal"),


    path('producto/lista/', Producto_Lista.as_view(), name="Producto_Lista"),
    path('producto/crear/', Producto_Crear.as_view(), name="Producto_Crear"),
    path('producto/editar/<int:pk>/', Producto_Editar.as_view(), name="Producto_Editar"),
    path('producto/eliminar/<int:pk>/', Producto_Eliminar.as_view(), name="Producto_Eliminar"),

    path('cliente/lista/', Cliente_Lista.as_view(), name="Cliente_Lista"),
    path('cliente/crear/', Cliente_Crear.as_view(), name="Cliente_Crear"),
    path('cliente/editar/<int:pk>/', Cliente_Editar.as_view(), name="Cliente_Editar"),
    path('cliente/eliminar/<int:pk>/', Cliente_Eliminar.as_view(), name="Cliente_Eliminar"),
    path('cliente/ver/<int:pk>/', Cliente_Ver, name='Cliente_Ver'),


    path('venta/crear/', Venta_Crear, name='Venta_Crear'),
    path('venta/lista/', Venta_Lista.as_view(), name="Venta_Lista"),

    path('detalleventa/ver/<int:pk>/', Detalle_De_Venta_Ver, name='Detalle_De_Venta_Ver'),

    path('venta/eliminar/<int:pk>/', Venta_Eliminar, name='Venta_Eliminar'),

]

login/urls.py
from django.urls import path

# del modulo views importamos la clase Inicio_De_Sesion
from .views import Inicio_De_Sesion,LogoutView

urlpatterns = [
    path('', Inicio_De_Sesion.as_view(),name="Iniciar_Sesion"),
    path('logout', LogoutView.as_view(),name="Cerrar_Sesion"),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView 

class Index(TemplateView):
    template_name = "index.html"

homepage/templates/index.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Cover Template · Bootstrap</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'Bootstrap_core_v4.5.0_CSS.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'Custom_Styles.css'%}" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">Tienda Saby</h3>
      <nav class="nav nav-masthead justify-content-center">

	      <a class="nav-link active" href="{% url 'index' %}">Homepage</a>

	<!-- Si el usuario esta ya esta logueado se mostrar el nombre del usuario . de lo contrario se mostara la opcion de login , para que se logue -->
	{% if request.user.is_authenticated %}
		<a class="nav-link" href="{% url 'erp:Panel_Principal' %}"> {{ request.user.username }} </a>
	{% else %}
		<a class="nav-link" href="{% url 'Iniciar_Sesion' %}">Acceder</a>
	{% endif %}

      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Bienvenido</h1>
    <!-- 
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
    </p>
    -->
  </main>


  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>© 2023, Tienda Saby. Todos los derechos reservados. </p>
    </div>
  </footer>
</div>
</body>
</html>